# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class UpdateLLMConfigRequest(BaseModel):
    """
    UpdateLLMConfig
    """ # noqa: E501
    api_key: StrictStr
    conversation_id: Optional[StrictInt] = None
    id: Optional[StrictInt] = None
    location: Optional[StrictStr] = None
    model: StrictStr
    project_id: Optional[StrictStr] = None
    provider: StrictStr
    temperature: Union[StrictFloat, StrictInt]
    tenant_id: StrictInt
    workflow_id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["api_key", "conversation_id", "id", "location", "model", "project_id", "provider", "temperature", "tenant_id", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateLLMConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateLLMConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key": obj.get("api_key"),
            "conversation_id": obj.get("conversation_id"),
            "id": obj.get("id"),
            "location": obj.get("location"),
            "model": obj.get("model"),
            "project_id": obj.get("project_id"),
            "provider": obj.get("provider"),
            "temperature": obj.get("temperature"),
            "tenant_id": obj.get("tenant_id"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


