/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateTenantRequest : CreateTenant
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTenantRequest {
    #[serde(rename = "determine_conversation_with_agent")]
    pub determine_conversation_with_agent: i64,
    #[serde(rename = "determine_conversation_with_narrative")]
    pub determine_conversation_with_narrative: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
    #[serde(rename = "username")]
    pub username: String,
}

impl CreateTenantRequest {
    /// CreateTenant
    pub fn new(determine_conversation_with_agent: i64, determine_conversation_with_narrative: String, tenant_id: i64, username: String) -> CreateTenantRequest {
        CreateTenantRequest {
            determine_conversation_with_agent,
            determine_conversation_with_narrative,
            tenant_id,
            username,
        }
    }
}

