/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "internal", skip_serializing_if = "Option::is_none")]
    pub internal: Option<Box<models::CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal>>,
    /// Required. The name of the function to call. Must start with a letter or an underscore. Must be a-z, A-Z, 0-9, or contain underscores, dots and dashes, with a maximum length of 64.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parameters")]
    pub parameters: serde_json::Value,
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<serde_json::Value>,
}

impl CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner {
    pub fn new(description: String, name: String, parameters: serde_json::Value) -> CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner {
        CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner {
            description,
            id: None,
            internal: None,
            name,
            parameters,
            response: None,
        }
    }
}

