/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateConversationRequest : CreateConversation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConversationRequest {
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
}

impl CreateConversationRequest {
    /// CreateConversation
    pub fn new(tenant_id: i64) -> CreateConversationRequest {
        CreateConversationRequest {
            tenant_id,
        }
    }
}

