/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal {
    pub fn new(provider: String) -> CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal {
        CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal {
            provider,
            tags: None,
        }
    }
}

