/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConversationResponse {
    #[serde(rename = "conversation_id")]
    pub conversation_id: i64,
}

impl CreateConversationResponse {
    pub fn new(conversation_id: i64) -> CreateConversationResponse {
        CreateConversationResponse {
            conversation_id,
        }
    }
}

