/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAgentResponse {
    #[serde(rename = "id")]
    pub id: i64,
}

impl CreateAgentResponse {
    pub fn new(id: i64) -> CreateAgentResponse {
        CreateAgentResponse {
            id,
        }
    }
}

