/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAgentRequestAgentsInnerRulesInnerToolsInner {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "function_declarations")]
    pub function_declarations: Vec<models::CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CreateAgentRequestAgentsInnerRulesInnerToolsInner {
    pub fn new(function_declarations: Vec<models::CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner>) -> CreateAgentRequestAgentsInnerRulesInnerToolsInner {
        CreateAgentRequestAgentsInnerRulesInnerToolsInner {
            description: None,
            function_declarations,
            id: None,
            name: None,
        }
    }
}

