/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateConversationUnderTenantRequest : CreateConversation (under a tenant)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConversationUnderTenantRequest {
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl CreateConversationUnderTenantRequest {
    /// CreateConversation (under a tenant)
    pub fn new() -> CreateConversationUnderTenantRequest {
        CreateConversationUnderTenantRequest {
            tags: None,
            title: None,
        }
    }
}

