/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateWorkflowUnderTenantRequest : CreateWorkflow (under a tenant)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkflowUnderTenantRequest {
    #[serde(rename = "agent_id", skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<i64>,
    #[serde(rename = "cached_content", skip_serializing_if = "Option::is_none")]
    pub cached_content: Option<serde_json::Value>,
    #[serde(rename = "conversation_id", skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<i64>,
    #[serde(rename = "cron", skip_serializing_if = "Option::is_none")]
    pub cron: Option<String>,
    #[serde(rename = "freeform")]
    pub freeform: bool,
    #[serde(rename = "generation_config", skip_serializing_if = "Option::is_none")]
    pub generation_config: Option<Box<models::CreateWorkflowUnderTenantRequestGenerationConfig>>,
    #[serde(rename = "input")]
    pub input: String,
    #[serde(rename = "input_event_weight", skip_serializing_if = "Option::is_none")]
    pub input_event_weight: Option<f64>,
    #[serde(rename = "output_event_weight", skip_serializing_if = "Option::is_none")]
    pub output_event_weight: Option<f64>,
}

impl CreateWorkflowUnderTenantRequest {
    /// CreateWorkflow (under a tenant)
    pub fn new(freeform: bool, input: String) -> CreateWorkflowUnderTenantRequest {
        CreateWorkflowUnderTenantRequest {
            agent_id: None,
            cached_content: None,
            conversation_id: None,
            cron: None,
            freeform,
            generation_config: None,
            input,
            input_event_weight: None,
            output_event_weight: None,
        }
    }
}

