/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkflowResponse {
    #[serde(rename = "workflow_id")]
    pub workflow_id: i64,
}

impl CreateWorkflowResponse {
    pub fn new(workflow_id: i64) -> CreateWorkflowResponse {
        CreateWorkflowResponse {
            workflow_id,
        }
    }
}

