/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateAgentRequest : CreateAgent
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAgentRequest {
    #[serde(rename = "agents")]
    pub agents: Vec<models::CreateAgentRequestAgentsInner>,
}

impl CreateAgentRequest {
    /// CreateAgent
    pub fn new(agents: Vec<models::CreateAgentRequestAgentsInner>) -> CreateAgentRequest {
        CreateAgentRequest {
            agents,
        }
    }
}

