/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTenantResponse {
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
}

impl CreateTenantResponse {
    pub fn new(tenant_id: i64) -> CreateTenantResponse {
        CreateTenantResponse {
            tenant_id,
        }
    }
}

