/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolUpsert : Payload for `/tool` PUT
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolUpsert {
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
    #[serde(rename = "tools")]
    pub tools: Vec<models::CreateAgentRequestAgentsInnerRulesInnerToolsInner>,
}

impl ToolUpsert {
    /// Payload for `/tool` PUT
    pub fn new(tenant_id: i64, tools: Vec<models::CreateAgentRequestAgentsInnerRulesInnerToolsInner>) -> ToolUpsert {
        ToolUpsert {
            tenant_id,
            tools,
        }
    }
}

