/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpsertAgentRequest : UpsertAgent (under a tenant)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertAgentRequest {
    #[serde(rename = "agents")]
    pub agents: Vec<models::UpsertAgentRequestAgentsInner>,
}

impl UpsertAgentRequest {
    /// UpsertAgent (under a tenant)
    pub fn new(agents: Vec<models::UpsertAgentRequestAgentsInner>) -> UpsertAgentRequest {
        UpsertAgentRequest {
            agents,
        }
    }
}

