/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertAgentRequestAgentsInner {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "edges")]
    pub edges: Vec<models::UpsertAgentRequestAgentsInnerEdgesInner>,
    #[serde(rename = "examples", skip_serializing_if = "Option::is_none")]
    pub examples: Option<Vec<String>>,
    /// The info the agent expects in its prompt
    #[serde(rename = "expected_input")]
    pub expected_input: String,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "is_default", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "rules")]
    pub rules: Vec<models::UpsertAgentRequestAgentsInnerRulesInner>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
    #[serde(rename = "tools")]
    pub tools: Vec<models::UpsertAgentRequestAgentsInnerRulesInnerToolsInner>,
}

impl UpsertAgentRequestAgentsInner {
    pub fn new(created_at: String, description: String, edges: Vec<models::UpsertAgentRequestAgentsInnerEdgesInner>, expected_input: String, id: i64, name: String, rules: Vec<models::UpsertAgentRequestAgentsInnerRulesInner>, tenant_id: i64, tools: Vec<models::UpsertAgentRequestAgentsInnerRulesInnerToolsInner>) -> UpsertAgentRequestAgentsInner {
        UpsertAgentRequestAgentsInner {
            created_at,
            description,
            edges,
            examples: None,
            expected_input,
            id,
            is_default: None,
            name,
            rules,
            tags: None,
            tenant_id,
            tools,
        }
    }
}

