/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertAgentRequestAgentsInnerEdgesInner {
    /// These are rule IDs that act as conditions to prevent an agent being called unless all the conditions in this list are true.  0 or more conditions under which the source agent can invoke the associated [target] [Agent] If empty, the target can be invoked under any circumstances
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<i64>>,
    /// If two edges could be invoked and both are not required then the highest priority one should be executed
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// A JavaScript condition which must evaluate to true for the agent to be executed
    #[serde(rename = "script_condition", skip_serializing_if = "Option::is_none")]
    pub script_condition: Option<String>,
    /// The agent ID that should be called if [script_condition] or any of the [conditions] are true
    #[serde(rename = "target_agent_id")]
    pub target_agent_id: i64,
}

impl UpsertAgentRequestAgentsInnerEdgesInner {
    pub fn new(target_agent_id: i64) -> UpsertAgentRequestAgentsInnerEdgesInner {
        UpsertAgentRequestAgentsInnerEdgesInner {
            conditions: None,
            priority: None,
            script_condition: None,
            target_agent_id,
        }
    }
}

