=begin
#

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Worka::UpsertAgentRequestAgentsInnerRulesInnerToolsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Worka::UpsertAgentRequestAgentsInnerRulesInnerToolsInner do
  let(:instance) { Worka::UpsertAgentRequestAgentsInnerRulesInnerToolsInner.new }

  describe 'test an instance of UpsertAgentRequestAgentsInnerRulesInnerToolsInner' do
    it 'should create an instance of UpsertAgentRequestAgentsInnerRulesInnerToolsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Worka::UpsertAgentRequestAgentsInnerRulesInnerToolsInner)
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "function_declarations"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
