/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner
 */
class CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerTest {
    private final CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner model = new CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner();

    /**
     * Model tests for CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner
     */
    @Test
    void testCreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner() {
        // TODO: test CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'internal'
     */
    @Test
    void internalTest() {
        // TODO: test internal
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'response'
     */
    @Test
    void responseTest() {
        // TODO: test response
    }

}
