/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CreateWorkflowRequestGenerationConfig;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateWorkflowRequest
 */
class CreateWorkflowRequestTest {
    private final CreateWorkflowRequest model = new CreateWorkflowRequest();

    /**
     * Model tests for CreateWorkflowRequest
     */
    @Test
    void testCreateWorkflowRequest() {
        // TODO: test CreateWorkflowRequest
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'cachedContent'
     */
    @Test
    void cachedContentTest() {
        // TODO: test cachedContent
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'cron'
     */
    @Test
    void cronTest() {
        // TODO: test cron
    }

    /**
     * Test the property 'freeform'
     */
    @Test
    void freeformTest() {
        // TODO: test freeform
    }

    /**
     * Test the property 'generationConfig'
     */
    @Test
    void generationConfigTest() {
        // TODO: test generationConfig
    }

    /**
     * Test the property 'input'
     */
    @Test
    void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'inputEventWeight'
     */
    @Test
    void inputEventWeightTest() {
        // TODO: test inputEventWeight
    }

    /**
     * Test the property 'outputEventWeight'
     */
    @Test
    void outputEventWeightTest() {
        // TODO: test outputEventWeight
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    void tenantIdTest() {
        // TODO: test tenantId
    }

}
