/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateWorkflowUnderTenantRequestGenerationConfig
 */
class CreateWorkflowUnderTenantRequestGenerationConfigTest {
    private final CreateWorkflowUnderTenantRequestGenerationConfig model = new CreateWorkflowUnderTenantRequestGenerationConfig();

    /**
     * Model tests for CreateWorkflowUnderTenantRequestGenerationConfig
     */
    @Test
    void testCreateWorkflowUnderTenantRequestGenerationConfig() {
        // TODO: test CreateWorkflowUnderTenantRequestGenerationConfig
    }

    /**
     * Test the property 'candidateCount'
     */
    @Test
    void candidateCountTest() {
        // TODO: test candidateCount
    }

    /**
     * Test the property 'maxOutputTokens'
     */
    @Test
    void maxOutputTokensTest() {
        // TODO: test maxOutputTokens
    }

    /**
     * Test the property 'stopSequences'
     */
    @Test
    void stopSequencesTest() {
        // TODO: test stopSequences
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'topK'
     */
    @Test
    void topKTest() {
        // TODO: test topK
    }

    /**
     * Test the property 'topP'
     */
    @Test
    void topPTest() {
        // TODO: test topP
    }

}
