/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateConversationResponse
 */
class CreateConversationResponseTest {
    private final CreateConversationResponse model = new CreateConversationResponse();

    /**
     * Model tests for CreateConversationResponse
     */
    @Test
    void testCreateConversationResponse() {
        // TODO: test CreateConversationResponse
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    void conversationIdTest() {
        // TODO: test conversationId
    }

}
