/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateAgentRequestAgentsInnerEdgesInner
 */
class CreateAgentRequestAgentsInnerEdgesInnerTest {
    private final CreateAgentRequestAgentsInnerEdgesInner model = new CreateAgentRequestAgentsInnerEdgesInner();

    /**
     * Model tests for CreateAgentRequestAgentsInnerEdgesInner
     */
    @Test
    void testCreateAgentRequestAgentsInnerEdgesInner() {
        // TODO: test CreateAgentRequestAgentsInnerEdgesInner
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'priority'
     */
    @Test
    void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'scriptCondition'
     */
    @Test
    void scriptConditionTest() {
        // TODO: test scriptCondition
    }

    /**
     * Test the property 'targetAgentId'
     */
    @Test
    void targetAgentIdTest() {
        // TODO: test targetAgentId
    }

}
