/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateLLMConfigRequest
 */
class UpdateLLMConfigRequestTest {
    private final UpdateLLMConfigRequest model = new UpdateLLMConfigRequest();

    /**
     * Model tests for UpdateLLMConfigRequest
     */
    @Test
    void testUpdateLLMConfigRequest() {
        // TODO: test UpdateLLMConfigRequest
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'location'
     */
    @Test
    void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'model'
     */
    @Test
    void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'provider'
     */
    @Test
    void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'workflowId'
     */
    @Test
    void workflowIdTest() {
        // TODO: test workflowId
    }

}
