/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.UpsertAgentRequestAgentsInnerRulesInnerToolsInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpsertAgentRequestAgentsInnerRulesInner
 */
class UpsertAgentRequestAgentsInnerRulesInnerTest {
    private final UpsertAgentRequestAgentsInnerRulesInner model = new UpsertAgentRequestAgentsInnerRulesInner();

    /**
     * Model tests for UpsertAgentRequestAgentsInnerRulesInner
     */
    @Test
    void testUpsertAgentRequestAgentsInnerRulesInner() {
        // TODO: test UpsertAgentRequestAgentsInnerRulesInner
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'position'
     */
    @Test
    void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'ruleCreatedAt'
     */
    @Test
    void ruleCreatedAtTest() {
        // TODO: test ruleCreatedAt
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'tools'
     */
    @Test
    void toolsTest() {
        // TODO: test tools
    }

    /**
     * Test the property 'versionCreatedAt'
     */
    @Test
    void versionCreatedAtTest() {
        // TODO: test versionCreatedAt
    }

    /**
     * Test the property 'versionId'
     */
    @Test
    void versionIdTest() {
        // TODO: test versionId
    }

}
