/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.UpsertAgentRequestAgentsInnerEdgesInner;
import org.openapitools.client.model.UpsertAgentRequestAgentsInnerRulesInner;
import org.openapitools.client.model.UpsertAgentRequestAgentsInnerRulesInnerToolsInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpsertAgentRequestAgentsInner
 */
class UpsertAgentRequestAgentsInnerTest {
    private final UpsertAgentRequestAgentsInner model = new UpsertAgentRequestAgentsInner();

    /**
     * Model tests for UpsertAgentRequestAgentsInner
     */
    @Test
    void testUpsertAgentRequestAgentsInner() {
        // TODO: test UpsertAgentRequestAgentsInner
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'edges'
     */
    @Test
    void edgesTest() {
        // TODO: test edges
    }

    /**
     * Test the property 'examples'
     */
    @Test
    void examplesTest() {
        // TODO: test examples
    }

    /**
     * Test the property 'expectedInput'
     */
    @Test
    void expectedInputTest() {
        // TODO: test expectedInput
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    void isDefaultTest() {
        // TODO: test isDefault
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rules'
     */
    @Test
    void rulesTest() {
        // TODO: test rules
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'tools'
     */
    @Test
    void toolsTest() {
        // TODO: test tools
    }

}
