/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.UpsertAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpsertAgentRequestAgentsInnerRulesInnerToolsInner
 */
class UpsertAgentRequestAgentsInnerRulesInnerToolsInnerTest {
    private final UpsertAgentRequestAgentsInnerRulesInnerToolsInner model = new UpsertAgentRequestAgentsInnerRulesInnerToolsInner();

    /**
     * Model tests for UpsertAgentRequestAgentsInnerRulesInnerToolsInner
     */
    @Test
    void testUpsertAgentRequestAgentsInnerRulesInnerToolsInner() {
        // TODO: test UpsertAgentRequestAgentsInnerRulesInnerToolsInner
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'functionDeclarations'
     */
    @Test
    void functionDeclarationsTest() {
        // TODO: test functionDeclarations
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
