/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* CreateTenant
*/
export class CreateTenantRequest {
    'determineConversationWithAgent': number;
    'determineConversationWithNarrative': string;
    'tenantId': number;
    'username': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "determineConversationWithAgent",
            "baseName": "determine_conversation_with_agent",
            "type": "number"
        },
        {
            "name": "determineConversationWithNarrative",
            "baseName": "determine_conversation_with_narrative",
            "type": "string"
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateTenantRequest.attributeTypeMap;
    }
}

