/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateAgentRequestAgentsInnerRulesInnerToolsInner } from './createAgentRequestAgentsInnerRulesInnerToolsInner';

export class CreateAgentRequestAgentsInnerRulesInner {
    'content': string;
    'description': string;
    'id': number;
    'name': string;
    'position': number;
    'ruleCreatedAt': Date;
    'tags'?: Array<string>;
    'tenantId': number;
    'tools'?: Array<CreateAgentRequestAgentsInnerRulesInnerToolsInner>;
    'versionCreatedAt': Date;
    'versionId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "ruleCreatedAt",
            "baseName": "rule_created_at",
            "type": "Date"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number"
        },
        {
            "name": "tools",
            "baseName": "tools",
            "type": "Array<CreateAgentRequestAgentsInnerRulesInnerToolsInner>"
        },
        {
            "name": "versionCreatedAt",
            "baseName": "version_created_at",
            "type": "Date"
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateAgentRequestAgentsInnerRulesInner.attributeTypeMap;
    }
}

