/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* CreateConversation
*/
export class CreateConversationRequest {
    'defaultStrategyId'?: number;
    'tenantId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "defaultStrategyId",
            "baseName": "default_strategy_id",
            "type": "number"
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateConversationRequest.attributeTypeMap;
    }
}

