/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateAgentRequestAgentsInnerRulesInnerToolsInner } from './createAgentRequestAgentsInnerRulesInnerToolsInner';

/**
* Payload for `/tool` PUT
*/
export class ToolUpsert {
    'tenantId': number;
    'tools': Array<CreateAgentRequestAgentsInnerRulesInnerToolsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number"
        },
        {
            "name": "tools",
            "baseName": "tools",
            "type": "Array<CreateAgentRequestAgentsInnerRulesInnerToolsInner>"
        }    ];

    static getAttributeTypeMap() {
        return ToolUpsert.attributeTypeMap;
    }
}

