/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* UpdateLLMConfig
*/
export class UpdateLLMConfigRequest {
    'apiKey': string;
    'conversationId'?: number;
    'id'?: number;
    'location'?: string;
    'model': string;
    'projectId'?: string;
    'provider': string;
    'temperature': number;
    'tenantId': number;
    'workflowId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiKey",
            "baseName": "api_key",
            "type": "string"
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number"
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number"
        },
        {
            "name": "workflowId",
            "baseName": "workflow_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateLLMConfigRequest.attributeTypeMap;
    }
}

