/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpsertAgentRequestAgentsInner } from './upsertAgentRequestAgentsInner';

/**
* UpsertAgent (under a tenant)
*/
export class UpsertAgentRequest {
    'agents': Array<UpsertAgentRequestAgentsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agents",
            "baseName": "agents",
            "type": "Array<UpsertAgentRequestAgentsInner>"
        }    ];

    static getAttributeTypeMap() {
        return UpsertAgentRequest.attributeTypeMap;
    }
}

