/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpsertAgentRequestAgentsInnerEdgesInner } from './upsertAgentRequestAgentsInnerEdgesInner';
import { UpsertAgentRequestAgentsInnerRulesInner } from './upsertAgentRequestAgentsInnerRulesInner';
import { UpsertAgentRequestAgentsInnerRulesInnerToolsInner } from './upsertAgentRequestAgentsInnerRulesInnerToolsInner';

export class UpsertAgentRequestAgentsInner {
    'createdAt'?: Date;
    'description': string;
    'edges'?: Array<UpsertAgentRequestAgentsInnerEdgesInner>;
    'examples'?: Array<string>;
    /**
    * The info the agent expects in its prompt
    */
    'expectedInput': string;
    'id': number;
    'isDefault'?: Date;
    'name': string;
    'rules': Array<UpsertAgentRequestAgentsInnerRulesInner>;
    'tags'?: Array<string>;
    'tenantId': number;
    /**
    * Tools that the agent itself has access to as opposed to those inherited from the rules
    */
    'tools'?: Array<UpsertAgentRequestAgentsInnerRulesInnerToolsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "edges",
            "baseName": "edges",
            "type": "Array<UpsertAgentRequestAgentsInnerEdgesInner>"
        },
        {
            "name": "examples",
            "baseName": "examples",
            "type": "Array<string>"
        },
        {
            "name": "expectedInput",
            "baseName": "expected_input",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "isDefault",
            "baseName": "is_default",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "rules",
            "baseName": "rules",
            "type": "Array<UpsertAgentRequestAgentsInnerRulesInner>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "tenantId",
            "baseName": "tenant_id",
            "type": "number"
        },
        {
            "name": "tools",
            "baseName": "tools",
            "type": "Array<UpsertAgentRequestAgentsInnerRulesInnerToolsInner>"
        }    ];

    static getAttributeTypeMap() {
        return UpsertAgentRequestAgentsInner.attributeTypeMap;
    }
}

