/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpsertAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner } from './upsertAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner';

export class UpsertAgentRequestAgentsInnerRulesInnerToolsInner {
    'description'?: string;
    'functionDeclarations': Array<UpsertAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner>;
    'id'?: number;
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "functionDeclarations",
            "baseName": "function_declarations",
            "type": "Array<UpsertAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpsertAgentRequestAgentsInnerRulesInnerToolsInner.attributeTypeMap;
    }
}

