/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateWorkflowRequestGenerationConfig
 */
@JsonPropertyOrder({
  CreateWorkflowRequestGenerationConfig.JSON_PROPERTY_CANDIDATE_COUNT,
  CreateWorkflowRequestGenerationConfig.JSON_PROPERTY_MAX_OUTPUT_TOKENS,
  CreateWorkflowRequestGenerationConfig.JSON_PROPERTY_STOP_SEQUENCES,
  CreateWorkflowRequestGenerationConfig.JSON_PROPERTY_TEMPERATURE,
  CreateWorkflowRequestGenerationConfig.JSON_PROPERTY_TOP_K,
  CreateWorkflowRequestGenerationConfig.JSON_PROPERTY_TOP_P
})
@JsonTypeName("CreateWorkflowRequest_generation_config")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T22:06:20.793426+01:00[Europe/London]", comments = "Generator version: 7.14.0")
public class CreateWorkflowRequestGenerationConfig {
  public static final String JSON_PROPERTY_CANDIDATE_COUNT = "candidate_count";
  @javax.annotation.Nullable
  private Integer candidateCount;

  public static final String JSON_PROPERTY_MAX_OUTPUT_TOKENS = "max_output_tokens";
  @javax.annotation.Nullable
  private Integer maxOutputTokens;

  public static final String JSON_PROPERTY_STOP_SEQUENCES = "stop_sequences";
  @javax.annotation.Nullable
  private List<String> stopSequences = new ArrayList<>();

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @javax.annotation.Nullable
  private Double temperature;

  public static final String JSON_PROPERTY_TOP_K = "top_k";
  @javax.annotation.Nullable
  private Integer topK;

  public static final String JSON_PROPERTY_TOP_P = "top_p";
  @javax.annotation.Nullable
  private Double topP;

  public CreateWorkflowRequestGenerationConfig() {
  }

  public CreateWorkflowRequestGenerationConfig candidateCount(@javax.annotation.Nullable Integer candidateCount) {
    
    this.candidateCount = candidateCount;
    return this;
  }

  /**
   * Get candidateCount
   * @return candidateCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANDIDATE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCandidateCount() {
    return candidateCount;
  }


  @JsonProperty(JSON_PROPERTY_CANDIDATE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCandidateCount(@javax.annotation.Nullable Integer candidateCount) {
    this.candidateCount = candidateCount;
  }

  public CreateWorkflowRequestGenerationConfig maxOutputTokens(@javax.annotation.Nullable Integer maxOutputTokens) {
    
    this.maxOutputTokens = maxOutputTokens;
    return this;
  }

  /**
   * Get maxOutputTokens
   * @return maxOutputTokens
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_OUTPUT_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxOutputTokens() {
    return maxOutputTokens;
  }


  @JsonProperty(JSON_PROPERTY_MAX_OUTPUT_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxOutputTokens(@javax.annotation.Nullable Integer maxOutputTokens) {
    this.maxOutputTokens = maxOutputTokens;
  }

  public CreateWorkflowRequestGenerationConfig stopSequences(@javax.annotation.Nullable List<String> stopSequences) {
    
    this.stopSequences = stopSequences;
    return this;
  }

  public CreateWorkflowRequestGenerationConfig addStopSequencesItem(String stopSequencesItem) {
    if (this.stopSequences == null) {
      this.stopSequences = new ArrayList<>();
    }
    this.stopSequences.add(stopSequencesItem);
    return this;
  }

  /**
   * Get stopSequences
   * @return stopSequences
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_SEQUENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStopSequences() {
    return stopSequences;
  }


  @JsonProperty(JSON_PROPERTY_STOP_SEQUENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopSequences(@javax.annotation.Nullable List<String> stopSequences) {
    this.stopSequences = stopSequences;
  }

  public CreateWorkflowRequestGenerationConfig temperature(@javax.annotation.Nullable Double temperature) {
    
    this.temperature = temperature;
    return this;
  }

  /**
   * Get temperature
   * @return temperature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTemperature() {
    return temperature;
  }


  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemperature(@javax.annotation.Nullable Double temperature) {
    this.temperature = temperature;
  }

  public CreateWorkflowRequestGenerationConfig topK(@javax.annotation.Nullable Integer topK) {
    
    this.topK = topK;
    return this;
  }

  /**
   * Get topK
   * @return topK
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOP_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTopK() {
    return topK;
  }


  @JsonProperty(JSON_PROPERTY_TOP_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopK(@javax.annotation.Nullable Integer topK) {
    this.topK = topK;
  }

  public CreateWorkflowRequestGenerationConfig topP(@javax.annotation.Nullable Double topP) {
    
    this.topP = topP;
    return this;
  }

  /**
   * Get topP
   * @return topP
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOP_P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTopP() {
    return topP;
  }


  @JsonProperty(JSON_PROPERTY_TOP_P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopP(@javax.annotation.Nullable Double topP) {
    this.topP = topP;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWorkflowRequestGenerationConfig createWorkflowRequestGenerationConfig = (CreateWorkflowRequestGenerationConfig) o;
    return Objects.equals(this.candidateCount, createWorkflowRequestGenerationConfig.candidateCount) &&
        Objects.equals(this.maxOutputTokens, createWorkflowRequestGenerationConfig.maxOutputTokens) &&
        Objects.equals(this.stopSequences, createWorkflowRequestGenerationConfig.stopSequences) &&
        Objects.equals(this.temperature, createWorkflowRequestGenerationConfig.temperature) &&
        Objects.equals(this.topK, createWorkflowRequestGenerationConfig.topK) &&
        Objects.equals(this.topP, createWorkflowRequestGenerationConfig.topP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(candidateCount, maxOutputTokens, stopSequences, temperature, topK, topP);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWorkflowRequestGenerationConfig {\n");
    sb.append("    candidateCount: ").append(toIndentedString(candidateCount)).append("\n");
    sb.append("    maxOutputTokens: ").append(toIndentedString(maxOutputTokens)).append("\n");
    sb.append("    stopSequences: ").append(toIndentedString(stopSequences)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    topK: ").append(toIndentedString(topK)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

