/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerRulesInnerToolsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateAgentRequestAgentsInnerRulesInner
 */
@JsonPropertyOrder({
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_CONTENT,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_DESCRIPTION,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_ID,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_NAME,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_POSITION,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_RULE_CREATED_AT,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_TAGS,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_TENANT_ID,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_TOOLS,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_VERSION_CREATED_AT,
  CreateAgentRequestAgentsInnerRulesInner.JSON_PROPERTY_VERSION_ID
})
@JsonTypeName("CreateAgentRequest_agents_inner_rules_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T22:06:20.793426+01:00[Europe/London]", comments = "Generator version: 7.14.0")
public class CreateAgentRequestAgentsInnerRulesInner {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private String content;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_POSITION = "position";
  @javax.annotation.Nonnull
  private Long position;

  public static final String JSON_PROPERTY_RULE_CREATED_AT = "rule_created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime ruleCreatedAt;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_TENANT_ID = "tenant_id";
  @javax.annotation.Nonnull
  private Long tenantId;

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @javax.annotation.Nullable
  private List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> tools = new ArrayList<>();

  public static final String JSON_PROPERTY_VERSION_CREATED_AT = "version_created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime versionCreatedAt;

  public static final String JSON_PROPERTY_VERSION_ID = "version_id";
  @javax.annotation.Nonnull
  private Long versionId;

  public CreateAgentRequestAgentsInnerRulesInner() {
  }

  public CreateAgentRequestAgentsInnerRulesInner content(@javax.annotation.Nonnull String content) {
    
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull String content) {
    this.content = content;
  }

  public CreateAgentRequestAgentsInnerRulesInner description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  public CreateAgentRequestAgentsInnerRulesInner id(@javax.annotation.Nonnull Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }

  public CreateAgentRequestAgentsInnerRulesInner name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public CreateAgentRequestAgentsInnerRulesInner position(@javax.annotation.Nonnull Long position) {
    
    this.position = position;
    return this;
  }

  /**
   * Get position
   * @return position
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPosition() {
    return position;
  }


  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPosition(@javax.annotation.Nonnull Long position) {
    this.position = position;
  }

  public CreateAgentRequestAgentsInnerRulesInner ruleCreatedAt(@javax.annotation.Nonnull OffsetDateTime ruleCreatedAt) {
    
    this.ruleCreatedAt = ruleCreatedAt;
    return this;
  }

  /**
   * Get ruleCreatedAt
   * @return ruleCreatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RULE_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getRuleCreatedAt() {
    return ruleCreatedAt;
  }


  @JsonProperty(JSON_PROPERTY_RULE_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRuleCreatedAt(@javax.annotation.Nonnull OffsetDateTime ruleCreatedAt) {
    this.ruleCreatedAt = ruleCreatedAt;
  }

  public CreateAgentRequestAgentsInnerRulesInner tags(@javax.annotation.Nullable List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public CreateAgentRequestAgentsInnerRulesInner addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }

  public CreateAgentRequestAgentsInnerRulesInner tenantId(@javax.annotation.Nonnull Long tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTenantId(@javax.annotation.Nonnull Long tenantId) {
    this.tenantId = tenantId;
  }

  public CreateAgentRequestAgentsInnerRulesInner tools(@javax.annotation.Nullable List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> tools) {
    
    this.tools = tools;
    return this;
  }

  public CreateAgentRequestAgentsInnerRulesInner addToolsItem(CreateAgentRequestAgentsInnerRulesInnerToolsInner toolsItem) {
    if (this.tools == null) {
      this.tools = new ArrayList<>();
    }
    this.tools.add(toolsItem);
    return this;
  }

  /**
   * Get tools
   * @return tools
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> getTools() {
    return tools;
  }


  @JsonProperty(JSON_PROPERTY_TOOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTools(@javax.annotation.Nullable List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> tools) {
    this.tools = tools;
  }

  public CreateAgentRequestAgentsInnerRulesInner versionCreatedAt(@javax.annotation.Nonnull OffsetDateTime versionCreatedAt) {
    
    this.versionCreatedAt = versionCreatedAt;
    return this;
  }

  /**
   * Get versionCreatedAt
   * @return versionCreatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getVersionCreatedAt() {
    return versionCreatedAt;
  }


  @JsonProperty(JSON_PROPERTY_VERSION_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersionCreatedAt(@javax.annotation.Nonnull OffsetDateTime versionCreatedAt) {
    this.versionCreatedAt = versionCreatedAt;
  }

  public CreateAgentRequestAgentsInnerRulesInner versionId(@javax.annotation.Nonnull Long versionId) {
    
    this.versionId = versionId;
    return this;
  }

  /**
   * Get versionId
   * @return versionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersionId() {
    return versionId;
  }


  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersionId(@javax.annotation.Nonnull Long versionId) {
    this.versionId = versionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAgentRequestAgentsInnerRulesInner createAgentRequestAgentsInnerRulesInner = (CreateAgentRequestAgentsInnerRulesInner) o;
    return Objects.equals(this.content, createAgentRequestAgentsInnerRulesInner.content) &&
        Objects.equals(this.description, createAgentRequestAgentsInnerRulesInner.description) &&
        Objects.equals(this.id, createAgentRequestAgentsInnerRulesInner.id) &&
        Objects.equals(this.name, createAgentRequestAgentsInnerRulesInner.name) &&
        Objects.equals(this.position, createAgentRequestAgentsInnerRulesInner.position) &&
        Objects.equals(this.ruleCreatedAt, createAgentRequestAgentsInnerRulesInner.ruleCreatedAt) &&
        Objects.equals(this.tags, createAgentRequestAgentsInnerRulesInner.tags) &&
        Objects.equals(this.tenantId, createAgentRequestAgentsInnerRulesInner.tenantId) &&
        Objects.equals(this.tools, createAgentRequestAgentsInnerRulesInner.tools) &&
        Objects.equals(this.versionCreatedAt, createAgentRequestAgentsInnerRulesInner.versionCreatedAt) &&
        Objects.equals(this.versionId, createAgentRequestAgentsInnerRulesInner.versionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, description, id, name, position, ruleCreatedAt, tags, tenantId, tools, versionCreatedAt, versionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAgentRequestAgentsInnerRulesInner {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    ruleCreatedAt: ").append(toIndentedString(ruleCreatedAt)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    versionCreatedAt: ").append(toIndentedString(versionCreatedAt)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

