/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateAgentRequestAgentsInnerRulesInnerToolsInner
 */
@JsonPropertyOrder({
  CreateAgentRequestAgentsInnerRulesInnerToolsInner.JSON_PROPERTY_DESCRIPTION,
  CreateAgentRequestAgentsInnerRulesInnerToolsInner.JSON_PROPERTY_FUNCTION_DECLARATIONS,
  CreateAgentRequestAgentsInnerRulesInnerToolsInner.JSON_PROPERTY_ID,
  CreateAgentRequestAgentsInnerRulesInnerToolsInner.JSON_PROPERTY_NAME
})
@JsonTypeName("CreateAgentRequest_agents_inner_rules_inner_tools_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T22:06:20.793426+01:00[Europe/London]", comments = "Generator version: 7.14.0")
public class CreateAgentRequestAgentsInnerRulesInnerToolsInner {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_FUNCTION_DECLARATIONS = "function_declarations";
  @javax.annotation.Nonnull
  private List<CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner> functionDeclarations = new ArrayList<>();

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public CreateAgentRequestAgentsInnerRulesInnerToolsInner() {
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInner description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInner functionDeclarations(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner> functionDeclarations) {
    
    this.functionDeclarations = functionDeclarations;
    return this;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInner addFunctionDeclarationsItem(CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner functionDeclarationsItem) {
    if (this.functionDeclarations == null) {
      this.functionDeclarations = new ArrayList<>();
    }
    this.functionDeclarations.add(functionDeclarationsItem);
    return this;
  }

  /**
   * Get functionDeclarations
   * @return functionDeclarations
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FUNCTION_DECLARATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner> getFunctionDeclarations() {
    return functionDeclarations;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION_DECLARATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFunctionDeclarations(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner> functionDeclarations) {
    this.functionDeclarations = functionDeclarations;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInner id(@javax.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInner name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAgentRequestAgentsInnerRulesInnerToolsInner createAgentRequestAgentsInnerRulesInnerToolsInner = (CreateAgentRequestAgentsInnerRulesInnerToolsInner) o;
    return Objects.equals(this.description, createAgentRequestAgentsInnerRulesInnerToolsInner.description) &&
        Objects.equals(this.functionDeclarations, createAgentRequestAgentsInnerRulesInnerToolsInner.functionDeclarations) &&
        Objects.equals(this.id, createAgentRequestAgentsInnerRulesInnerToolsInner.id) &&
        Objects.equals(this.name, createAgentRequestAgentsInnerRulesInnerToolsInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, functionDeclarations, id, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAgentRequestAgentsInnerRulesInnerToolsInner {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    functionDeclarations: ").append(toIndentedString(functionDeclarations)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

