/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerEdgesInner;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerRulesInner;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerRulesInnerToolsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateAgentRequestAgentsInner
 */
@JsonPropertyOrder({
  CreateAgentRequestAgentsInner.JSON_PROPERTY_CREATED_AT,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_DESCRIPTION,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_EDGES,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_EXAMPLES,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_EXPECTED_INPUT,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_ID,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_IS_DEFAULT,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_NAME,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_RULES,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_TAGS,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_TENANT_ID,
  CreateAgentRequestAgentsInner.JSON_PROPERTY_TOOLS
})
@JsonTypeName("CreateAgentRequest_agents_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T22:06:20.793426+01:00[Europe/London]", comments = "Generator version: 7.14.0")
public class CreateAgentRequestAgentsInner {
  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_EDGES = "edges";
  @javax.annotation.Nonnull
  private List<CreateAgentRequestAgentsInnerEdgesInner> edges = new ArrayList<>();

  public static final String JSON_PROPERTY_EXAMPLES = "examples";
  @javax.annotation.Nullable
  private List<String> examples = new ArrayList<>();

  public static final String JSON_PROPERTY_EXPECTED_INPUT = "expected_input";
  @javax.annotation.Nonnull
  private String expectedInput;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Long id;

  public static final String JSON_PROPERTY_IS_DEFAULT = "is_default";
  @javax.annotation.Nullable
  private OffsetDateTime isDefault;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_RULES = "rules";
  @javax.annotation.Nonnull
  private List<CreateAgentRequestAgentsInnerRulesInner> rules = new ArrayList<>();

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_TENANT_ID = "tenant_id";
  @javax.annotation.Nonnull
  private Long tenantId;

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @javax.annotation.Nonnull
  private List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> tools = new ArrayList<>();

  public CreateAgentRequestAgentsInner() {
  }

  public CreateAgentRequestAgentsInner createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public CreateAgentRequestAgentsInner description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  public CreateAgentRequestAgentsInner edges(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerEdgesInner> edges) {
    
    this.edges = edges;
    return this;
  }

  public CreateAgentRequestAgentsInner addEdgesItem(CreateAgentRequestAgentsInnerEdgesInner edgesItem) {
    if (this.edges == null) {
      this.edges = new ArrayList<>();
    }
    this.edges.add(edgesItem);
    return this;
  }

  /**
   * Get edges
   * @return edges
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EDGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CreateAgentRequestAgentsInnerEdgesInner> getEdges() {
    return edges;
  }


  @JsonProperty(JSON_PROPERTY_EDGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEdges(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerEdgesInner> edges) {
    this.edges = edges;
  }

  public CreateAgentRequestAgentsInner examples(@javax.annotation.Nullable List<String> examples) {
    
    this.examples = examples;
    return this;
  }

  public CreateAgentRequestAgentsInner addExamplesItem(String examplesItem) {
    if (this.examples == null) {
      this.examples = new ArrayList<>();
    }
    this.examples.add(examplesItem);
    return this;
  }

  /**
   * Get examples
   * @return examples
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExamples() {
    return examples;
  }


  @JsonProperty(JSON_PROPERTY_EXAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExamples(@javax.annotation.Nullable List<String> examples) {
    this.examples = examples;
  }

  public CreateAgentRequestAgentsInner expectedInput(@javax.annotation.Nonnull String expectedInput) {
    
    this.expectedInput = expectedInput;
    return this;
  }

  /**
   * The info the agent expects in its prompt
   * @return expectedInput
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPECTED_INPUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpectedInput() {
    return expectedInput;
  }


  @JsonProperty(JSON_PROPERTY_EXPECTED_INPUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpectedInput(@javax.annotation.Nonnull String expectedInput) {
    this.expectedInput = expectedInput;
  }

  public CreateAgentRequestAgentsInner id(@javax.annotation.Nonnull Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }

  public CreateAgentRequestAgentsInner isDefault(@javax.annotation.Nullable OffsetDateTime isDefault) {
    
    this.isDefault = isDefault;
    return this;
  }

  /**
   * Get isDefault
   * @return isDefault
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getIsDefault() {
    return isDefault;
  }


  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDefault(@javax.annotation.Nullable OffsetDateTime isDefault) {
    this.isDefault = isDefault;
  }

  public CreateAgentRequestAgentsInner name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public CreateAgentRequestAgentsInner rules(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerRulesInner> rules) {
    
    this.rules = rules;
    return this;
  }

  public CreateAgentRequestAgentsInner addRulesItem(CreateAgentRequestAgentsInnerRulesInner rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CreateAgentRequestAgentsInnerRulesInner> getRules() {
    return rules;
  }


  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRules(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerRulesInner> rules) {
    this.rules = rules;
  }

  public CreateAgentRequestAgentsInner tags(@javax.annotation.Nullable List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public CreateAgentRequestAgentsInner addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }

  public CreateAgentRequestAgentsInner tenantId(@javax.annotation.Nonnull Long tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTenantId(@javax.annotation.Nonnull Long tenantId) {
    this.tenantId = tenantId;
  }

  public CreateAgentRequestAgentsInner tools(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> tools) {
    
    this.tools = tools;
    return this;
  }

  public CreateAgentRequestAgentsInner addToolsItem(CreateAgentRequestAgentsInnerRulesInnerToolsInner toolsItem) {
    if (this.tools == null) {
      this.tools = new ArrayList<>();
    }
    this.tools.add(toolsItem);
    return this;
  }

  /**
   * Get tools
   * @return tools
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOOLS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> getTools() {
    return tools;
  }


  @JsonProperty(JSON_PROPERTY_TOOLS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTools(@javax.annotation.Nonnull List<CreateAgentRequestAgentsInnerRulesInnerToolsInner> tools) {
    this.tools = tools;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAgentRequestAgentsInner createAgentRequestAgentsInner = (CreateAgentRequestAgentsInner) o;
    return Objects.equals(this.createdAt, createAgentRequestAgentsInner.createdAt) &&
        Objects.equals(this.description, createAgentRequestAgentsInner.description) &&
        Objects.equals(this.edges, createAgentRequestAgentsInner.edges) &&
        Objects.equals(this.examples, createAgentRequestAgentsInner.examples) &&
        Objects.equals(this.expectedInput, createAgentRequestAgentsInner.expectedInput) &&
        Objects.equals(this.id, createAgentRequestAgentsInner.id) &&
        Objects.equals(this.isDefault, createAgentRequestAgentsInner.isDefault) &&
        Objects.equals(this.name, createAgentRequestAgentsInner.name) &&
        Objects.equals(this.rules, createAgentRequestAgentsInner.rules) &&
        Objects.equals(this.tags, createAgentRequestAgentsInner.tags) &&
        Objects.equals(this.tenantId, createAgentRequestAgentsInner.tenantId) &&
        Objects.equals(this.tools, createAgentRequestAgentsInner.tools);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, description, edges, examples, expectedInput, id, isDefault, name, rules, tags, tenantId, tools);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAgentRequestAgentsInner {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    edges: ").append(toIndentedString(edges)).append("\n");
    sb.append("    examples: ").append(toIndentedString(examples)).append("\n");
    sb.append("    expectedInput: ").append(toIndentedString(expectedInput)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

