/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal
 */
@JsonPropertyOrder({
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal.JSON_PROPERTY_PROVIDER,
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal.JSON_PROPERTY_TAGS
})
@JsonTypeName("CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T22:06:20.793426+01:00[Europe/London]", comments = "Generator version: 7.14.0")
public class CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal {
  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nonnull
  private String provider;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal() {
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal provider(@javax.annotation.Nonnull String provider) {
    
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal tags(@javax.annotation.Nullable List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal = (CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal) o;
    return Objects.equals(this.provider, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal.provider) &&
        Objects.equals(this.tags, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal {\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

