/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner
 */
@JsonPropertyOrder({
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.JSON_PROPERTY_DESCRIPTION,
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.JSON_PROPERTY_ID,
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.JSON_PROPERTY_INTERNAL,
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.JSON_PROPERTY_NAME,
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.JSON_PROPERTY_PARAMETERS,
  CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.JSON_PROPERTY_RESPONSE
})
@JsonTypeName("CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T22:06:20.793426+01:00[Europe/London]", comments = "Generator version: 7.14.0")
public class CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_INTERNAL = "internal";
  @javax.annotation.Nullable
  private CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal internal;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @javax.annotation.Nonnull
  private Object parameters;

  public static final String JSON_PROPERTY_RESPONSE = "response";
  @javax.annotation.Nullable
  private Object response;

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner() {
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner description(@javax.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner id(@javax.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner internal(@javax.annotation.Nullable CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal internal) {
    
    this.internal = internal;
    return this;
  }

  /**
   * Get internal
   * @return internal
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERNAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal getInternal() {
    return internal;
  }


  @JsonProperty(JSON_PROPERTY_INTERNAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternal(@javax.annotation.Nullable CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInnerInternal internal) {
    this.internal = internal;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Required. The name of the function to call. Must start with a letter or an underscore. Must be a-z, A-Z, 0-9, or contain underscores, dots and dashes, with a maximum length of 64.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner parameters(@javax.annotation.Nonnull Object parameters) {
    
    this.parameters = parameters;
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getParameters() {
    return parameters;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParameters(@javax.annotation.Nonnull Object parameters) {
    this.parameters = parameters;
  }

  public CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner response(@javax.annotation.Nullable Object response) {
    
    this.response = response;
    return this;
  }

  /**
   * Get response
   * @return response
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getResponse() {
    return response;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponse(@javax.annotation.Nullable Object response) {
    this.response = response;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner = (CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner) o;
    return Objects.equals(this.description, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.description) &&
        Objects.equals(this.id, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.id) &&
        Objects.equals(this.internal, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.internal) &&
        Objects.equals(this.name, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.name) &&
        Objects.equals(this.parameters, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.parameters) &&
        Objects.equals(this.response, createAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, internal, name, parameters, response);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    internal: ").append(toIndentedString(internal)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

