=begin
#

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Worka::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = Worka::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(Worka::DefaultApi)
    end
  end

  # unit tests for agent_put
  # @param create_agent_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateAgentResponse]
  describe 'agent_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for conversation_post
  # @param create_conversation_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateConversationResponse]
  describe 'conversation_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for llm_config_post
  # @param update_llm_config_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateLLMConfigResponse]
  describe 'llm_config_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tenant_post
  # @param create_tenant_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateTenantResponse]
  describe 'tenant_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tool_put
  # @param tool_upsert 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'tool_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workflow_id_get
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetWorkflowResponse]
  describe 'workflow_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workflow_post
  # @param create_workflow_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateWorkflowResponse]
  describe 'workflow_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
