# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.upsert_llm_config_request import UpsertLLMConfigRequest

class TestUpsertLLMConfigRequest(unittest.TestCase):
    """UpsertLLMConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertLLMConfigRequest:
        """Test UpsertLLMConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertLLMConfigRequest`
        """
        model = UpsertLLMConfigRequest()
        if include_optional:
            return UpsertLLMConfigRequest(
                api_key = '',
                conversation_id = 56,
                id = 56,
                location = '',
                model = '',
                project_id = '',
                provider = '',
                temperature = 1.337,
                workflow_id = 56
            )
        else:
            return UpsertLLMConfigRequest(
                api_key = '',
                model = '',
                provider = '',
                temperature = 1.337,
        )
        """

    def testUpsertLLMConfigRequest(self):
        """Test UpsertLLMConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
