# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.upsert_agent_request_agents_inner_rules_inner import UpsertAgentRequestAgentsInnerRulesInner

class TestUpsertAgentRequestAgentsInnerRulesInner(unittest.TestCase):
    """UpsertAgentRequestAgentsInnerRulesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertAgentRequestAgentsInnerRulesInner:
        """Test UpsertAgentRequestAgentsInnerRulesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertAgentRequestAgentsInnerRulesInner`
        """
        model = UpsertAgentRequestAgentsInnerRulesInner()
        if include_optional:
            return UpsertAgentRequestAgentsInnerRulesInner(
                content = '',
                description = '',
                id = 56,
                name = '',
                position = 56,
                rule_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    ''
                    ],
                tenant_id = 56,
                tools = [
                    worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner.UpsertAgentRequest_agents_inner_rules_inner_tools_inner(
                        description = '', 
                        function_declarations = [
                            worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner.UpsertAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner(
                                description = '', 
                                id = 56, 
                                internal = worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal.UpsertAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal(
                                    provider = '', 
                                    tags = [
                                        ''
                                        ], ), 
                                name = '', 
                                parameters = worka.models.parameters.parameters(), 
                                response = worka.models.response.response(), )
                            ], 
                        id = 56, 
                        name = '', )
                    ],
                version_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                version_id = 56
            )
        else:
            return UpsertAgentRequestAgentsInnerRulesInner(
                content = '',
                description = '',
                id = 56,
                name = '',
                position = 56,
                rule_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tenant_id = 56,
                version_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                version_id = 56,
        )
        """

    def testUpsertAgentRequestAgentsInnerRulesInner(self):
        """Test UpsertAgentRequestAgentsInnerRulesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
