# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.create_conversation_response import CreateConversationResponse

class TestCreateConversationResponse(unittest.TestCase):
    """CreateConversationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateConversationResponse:
        """Test CreateConversationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConversationResponse`
        """
        model = CreateConversationResponse()
        if include_optional:
            return CreateConversationResponse(
                conversation_id = 56
            )
        else:
            return CreateConversationResponse(
                conversation_id = 56,
        )
        """

    def testCreateConversationResponse(self):
        """Test CreateConversationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
