# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.create_workflow_request import CreateWorkflowRequest

class TestCreateWorkflowRequest(unittest.TestCase):
    """CreateWorkflowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkflowRequest:
        """Test CreateWorkflowRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkflowRequest`
        """
        model = CreateWorkflowRequest()
        if include_optional:
            return CreateWorkflowRequest(
                agent_id = 56,
                cached_content = None,
                conversation_id = 56,
                cron = '',
                freeform = True,
                generation_config = worka.models.create_workflow_request_generation_config.CreateWorkflowRequest_generation_config(
                    candidate_count = 56, 
                    max_output_tokens = 56, 
                    stop_sequences = [
                        ''
                        ], 
                    temperature = 1.337, 
                    top_k = 56, 
                    top_p = 1.337, ),
                input = '',
                input_event_weight = 1.337,
                output_event_weight = 1.337,
                tenant_id = 56
            )
        else:
            return CreateWorkflowRequest(
                freeform = True,
                input = '',
                tenant_id = 56,
        )
        """

    def testCreateWorkflowRequest(self):
        """Test CreateWorkflowRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
