# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.upsert_tool_request import UpsertToolRequest

class TestUpsertToolRequest(unittest.TestCase):
    """UpsertToolRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertToolRequest:
        """Test UpsertToolRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertToolRequest`
        """
        model = UpsertToolRequest()
        if include_optional:
            return UpsertToolRequest(
                tools = [
                    worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner.UpsertAgentRequest_agents_inner_rules_inner_tools_inner(
                        description = '', 
                        function_declarations = [
                            worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner.UpsertAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner(
                                description = '', 
                                id = 56, 
                                internal = worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal.UpsertAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal(
                                    provider = '', 
                                    tags = [
                                        ''
                                        ], ), 
                                name = '', 
                                parameters = worka.models.parameters.parameters(), 
                                response = worka.models.response.response(), )
                            ], 
                        id = 56, 
                        name = '', )
                    ]
            )
        else:
            return UpsertToolRequest(
                tools = [
                    worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner.UpsertAgentRequest_agents_inner_rules_inner_tools_inner(
                        description = '', 
                        function_declarations = [
                            worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner.UpsertAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner(
                                description = '', 
                                id = 56, 
                                internal = worka.models.upsert_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal.UpsertAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal(
                                    provider = '', 
                                    tags = [
                                        ''
                                        ], ), 
                                name = '', 
                                parameters = worka.models.parameters.parameters(), 
                                response = worka.models.response.response(), )
                            ], 
                        id = 56, 
                        name = '', )
                    ],
        )
        """

    def testUpsertToolRequest(self):
        """Test UpsertToolRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
