# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.create_conversation_under_tenant_request import CreateConversationUnderTenantRequest

class TestCreateConversationUnderTenantRequest(unittest.TestCase):
    """CreateConversationUnderTenantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateConversationUnderTenantRequest:
        """Test CreateConversationUnderTenantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConversationUnderTenantRequest`
        """
        model = CreateConversationUnderTenantRequest()
        if include_optional:
            return CreateConversationUnderTenantRequest(
                tags = [
                    ''
                    ],
                title = ''
            )
        else:
            return CreateConversationUnderTenantRequest(
        )
        """

    def testCreateConversationUnderTenantRequest(self):
        """Test CreateConversationUnderTenantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
