# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.create_workflow_request_generation_config import CreateWorkflowRequestGenerationConfig

class TestCreateWorkflowRequestGenerationConfig(unittest.TestCase):
    """CreateWorkflowRequestGenerationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkflowRequestGenerationConfig:
        """Test CreateWorkflowRequestGenerationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkflowRequestGenerationConfig`
        """
        model = CreateWorkflowRequestGenerationConfig()
        if include_optional:
            return CreateWorkflowRequestGenerationConfig(
                candidate_count = 56,
                max_output_tokens = 56,
                stop_sequences = [
                    ''
                    ],
                temperature = 1.337,
                top_k = 56,
                top_p = 1.337
            )
        else:
            return CreateWorkflowRequestGenerationConfig(
        )
        """

    def testCreateWorkflowRequestGenerationConfig(self):
        """Test CreateWorkflowRequestGenerationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
