# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_agent_put(self) -> None:
        """Test case for agent_put

        """
        pass

    def test_conversation_post(self) -> None:
        """Test case for conversation_post

        """
        pass

    def test_llm_config_post(self) -> None:
        """Test case for llm_config_post

        """
        pass

    def test_tenant_post(self) -> None:
        """Test case for tenant_post

        """
        pass

    def test_tool_put(self) -> None:
        """Test case for tool_put

        """
        pass

    def test_workflow_id_get(self) -> None:
        """Test case for workflow_id_get

        """
        pass

    def test_workflow_post(self) -> None:
        """Test case for workflow_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
