# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.upsert_agent_request_agents_inner_edges_inner import UpsertAgentRequestAgentsInnerEdgesInner

class TestUpsertAgentRequestAgentsInnerEdgesInner(unittest.TestCase):
    """UpsertAgentRequestAgentsInnerEdgesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertAgentRequestAgentsInnerEdgesInner:
        """Test UpsertAgentRequestAgentsInnerEdgesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertAgentRequestAgentsInnerEdgesInner`
        """
        model = UpsertAgentRequestAgentsInnerEdgesInner()
        if include_optional:
            return UpsertAgentRequestAgentsInnerEdgesInner(
                conditions = [
                    56
                    ],
                priority = 56,
                script_condition = '',
                target_agent_id = 56
            )
        else:
            return UpsertAgentRequestAgentsInnerEdgesInner(
                conditions = [
                    56
                    ],
                priority = 56,
                target_agent_id = 56,
        )
        """

    def testUpsertAgentRequestAgentsInnerEdgesInner(self):
        """Test UpsertAgentRequestAgentsInnerEdgesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
