# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from worka.models.create_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner import CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner

class TestCreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner(unittest.TestCase):
    """CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner:
        """Test CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner`
        """
        model = CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner()
        if include_optional:
            return CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner(
                description = '',
                id = 56,
                internal = worka.models.create_agent_request_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal.CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal(
                    provider = '', 
                    tags = [
                        ''
                        ], ),
                name = '',
                parameters = worka.models.parameters.parameters(),
                response = worka.models.response.response()
            )
        else:
            return CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner(
                description = '',
                name = '',
                parameters = worka.models.parameters.parameters(),
        )
        """

    def testCreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner(self):
        """Test CreateAgentRequestAgentsInnerRulesInnerToolsInnerFunctionDeclarationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
